# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PCI) += pci.o
obj-$(CONFIG_LKL_PCI_KUNIT_TEST) += pci_test.o
obj-$(CONFIG_PCI_MSI) += pci-msi.o
obj-$(CONFIG_LKL_PCI_MSI_KUNIT_TEST) += pci-msi-test.o
